import type { AppLanguage } from "@/lib/preferences";

export const copy = {
  en: {
    header: {
      navLabel: "Primary",
      links: [
        { href: "/", label: "Home" },
        { href: "/mappings", label: "Mappings" },
        { href: "/groups", label: "Groups" },
        { href: "/parameters", label: "Parameters" },
        { href: "/approvals", label: "Approvals" },
        { href: "/audit", label: "Audit" },
        { href: "/imports", label: "Imports" },
        { href: "/help", label: "Help" },
        { href: "/api/health/db", label: "DB Health" },
      ],
      themeToggle: "Switch color theme",
      languageToggle: "Switch language",
      lightTheme: "Light",
      darkTheme: "Dark",
      english: "EN",
      spanish: "ES",
      logout: "Logout",
    },
    home: {
      eyebrow: "MDM Lite / Reference Data Manager",
      title: "A starting foundation to govern business rules without hardcoding.",
      description:
        "The repository is already organized with documentation, SQL schema, demo dataset, and an application scaffold to launch the MVP on standard PostgreSQL.",
      primaryCta: "Open mappings",
      secondaryCta: "Open parameters",
      panelTitle: "Launch status",
      panelItems: [
        "Documentation organized in docs/",
        "Demo dataset available in data/demo/",
        "Initial schema stored in db/schema/",
        "Base stack defined with Next.js + TypeScript",
        "Local web port configured at",
        "DB health check available at /api/health/db",
      ],
      statLabels: {
        mappings: "mappings",
        groups: "groups",
        parameters: "parameters",
      },
      cards: [
        {
          title: "Master Data",
          text: "Mappings, groups, and parameters with effective dating and auditability.",
        },
        {
          title: "Demo Import",
          text: "CSV or XLSX loading with preview and simple manual correction.",
        },
        {
          title: "Technical Consumption",
          text: "Initial contract through SQL views, prepared for API or MCP in future phases.",
        },
        {
          title: "Simple Operations",
          text: "Single-company MVP with one initial admin and a lightweight approval flow.",
        },
      ],
      demoReset: {
        eyebrow: "Guided Demo",
        title: "Reset and load the teaching scenario",
        description:
          "Wipes operational rules and reloads a short, explainable story for CLIENT and PRODUCT, with approved records, pending approvals, and audit history.",
        cta: "Load guided demo",
        processing: "Loading demo...",
        confirm:
          "This will delete current operational mappings, groups, parameters, imports, and audit rows, then load the guided demo scenario. Continue?",
        helpCta: "Open functional guide",
        note: "Recommended before a live walkthrough, training, or first-contact session.",
        success: "Guided demo loaded successfully.",
        error: "Could not load the guided demo",
      },
    },
    mappingsPage: {
      eyebrow: "Operational View",
      title: "Active mappings",
      description:
        "Approved, active, and effective rules ready for technical consumption. This view already reads from the remote Supabase database.",
      recordsLabel: "records",
      sourceLabel: "Source: vw_mdm_mapping_rule_active",
      filterPlaceholder: "Search by source, target, or rule set",
    },
    groupsPage: {
      eyebrow: "Operational View",
      title: "Active groups",
      description: "Approved, active, and effective grouping rules ready for reporting or consolidation.",
      recordsLabel: "records",
      sourceLabel: "Source: vw_mdm_group_rule_active",
      filterPlaceholder: "Search by member, group, or rule set",
    },
    parametersPage: {
      eyebrow: "Operational View",
      title: "Active parameters",
      description:
        "Effective parameters exposed with a simple functional scope. The current demo reflects PVP factors by customer.",
      recordsLabel: "records",
      sourceLabel: "Source: vw_mdm_parameter_active",
      filterPlaceholder: "Search by key, domain, or scope",
    },
    importsPage: {
      eyebrow: "Operations",
      title: "Data import",
      description:
        "Initial console to reload the project demo dataset or upload manual csv/xlsx files into mappings, groups, and parameters.",
    },
    forms: {
      filterSubmit: "Filter",
      mappingCreate: {
        eyebrow: "Manual Entry",
        title: "New mapping",
        description: "Lightweight form to create a mapping without relying on file import.",
        sourceValueLabel: "Source value",
        sourceValuePlaceholder: "ALDI SAN ISIDRO SUPERMERCADOS, S.L.",
        targetValueLabel: "Target value",
        targetValuePlaceholder: "ALDI SUPERMERCADOS",
        validFromLabel: "Effective from",
        commentsLabel: "Comments",
        commentsPlaceholder: "Manual entry from UI",
        submitting: "Saving...",
        submit: "Create mapping",
        success: "Mapping created successfully.",
      },
      mappingTable: {
        empty: "There are no active mappings for the current filter.",
        headers: ["Entity", "Source key", "Source value", "Target value", "Rule set", "Effective date", "Action"],
        edit: "Edit",
        close: "Close",
        sourceValueLabel: "Source value",
        targetValueLabel: "Target value",
        validFromLabel: "Effective from",
        commentsLabel: "Comments",
        commentsPlaceholder: "Manual update from UI",
        saving: "Saving...",
        save: "Save changes",
        cancel: "Cancel",
        success: "Mapping updated.",
      },
      groupCreate: {
        eyebrow: "Manual Entry",
        title: "New group",
        description: "Lightweight form to create a commercial grouping without relying on import.",
        memberLabel: "Member",
        memberPlaceholder: "EROSKI S.COOP.",
        groupLabel: "Group",
        groupPlaceholder: "EROSKY",
        validFromLabel: "Effective from",
        commentsLabel: "Comments",
        commentsPlaceholder: "Manual entry from UI",
        submitting: "Saving...",
        submit: "Create group",
        success: "Group created successfully.",
      },
      groupTable: {
        empty: "There are no active groups for the current filter.",
        headers: ["Entity", "Member", "Group", "Label", "Rule set", "Effective date", "Action"],
        edit: "Edit",
        close: "Close",
        memberLabel: "Member",
        groupLabel: "Group",
        validFromLabel: "Effective from",
        commentsLabel: "Comments",
        commentsPlaceholder: "Manual update from UI",
        saving: "Saving...",
        save: "Save changes",
        cancel: "Cancel",
        success: "Group updated.",
      },
      parameterCreate: {
        eyebrow: "Manual Entry",
        title: "New parameter",
        description: "Lightweight form to create active parameters with a simple scope by customer or another context.",
        parameterKeyLabel: "Key",
        parameterValueLabel: "Value",
        parameterValuePlaceholder: "1.05",
        domainLabel: "Domain",
        scopeTypeLabel: "Scope type",
        scopeValueLabel: "Scope value",
        scopeValuePlaceholder: "MARJANE",
        validFromLabel: "Effective from",
        commentsLabel: "Comments",
        commentsPlaceholder: "Manual entry from UI",
        submitting: "Saving...",
        submit: "Create parameter",
        success: "Parameter created successfully.",
      },
      parameterTable: {
        empty: "There are no active parameters for the current filter.",
        headers: ["Key", "Value", "Type", "Domain", "Scope", "Effective date", "Action"],
        edit: "Edit",
        close: "Close",
        global: "GLOBAL",
        parameterKeyLabel: "Key",
        parameterValueLabel: "Value",
        domainLabel: "Domain",
        scopeTypeLabel: "Scope type",
        scopeValueLabel: "Scope value",
        validFromLabel: "Effective from",
        commentsLabel: "Comments",
        commentsPlaceholder: "Manual update from UI",
        saving: "Saving...",
        save: "Save changes",
        cancel: "Cancel",
        success: "Parameter updated.",
      },
      importsConsole: {
        demoEyebrow: "Demo Dataset",
        demoTitle: "Reload project workbook",
        demoDescription:
          "Run the import for the demo Excel workbook stored in data/demo/ to restore base mappings, groups, and parameters.",
        demoCta: "Import server demo",
        uploadEyebrow: "Manual Load",
        uploadTitle: "Upload CSV or XLSX",
        uploadDescription: "Import a file for mappings, groups, or parameters. The first worksheet in the file is used.",
        targetLabel: "Import type",
        targetOptions: {
          mappings: "Mappings",
          groups: "Groups",
          parameters: "Parameters",
        },
        fileLabel: "File",
        uploadCta: "Upload and import",
        processing: "Processing...",
        resultEyebrow: "Result",
        resultTitle: "Latest execution status",
        noResult: "There have been no recent executions in this session.",
        success: "Import completed successfully.",
        error: "Import failed.",
      },
    },
    helpNav: {
      ariaLabel: "Help sections",
      links: {
        overview: "Overview",
        demo: "Guided demo",
        executive: "Executive FAQ",
        functional: "Functional Guide",
        positioning: "Positioning",
        platforms: "Medallion and ELT",
      },
    },
    helpOverview: {
      sections: [
        {
          title: "Guided demo",
          href: "/help/demo",
          text: "Step-by-step route to load the curated demo and explain the product alone from the browser, including what to click and what to observe.",
        },
        {
          title: "Executive FAQ",
          href: "/help/executive",
          text: "Explains in executive language what problem MDM Lite solves, who it really competes with, and why it does not replace Purview, Unity Catalog, or enterprise catalogs.",
        },
        {
          title: "Functional Guide",
          href: "/help/functional",
          text: "Explains what each module does, how information is loaded, and how MDM Lite participates in a traditional ETL run.",
        },
        {
          title: "Positioning",
          href: "/help/positioning",
          text: "Clarifies that MDM Lite does not compete with Purview, Unity Catalog, or other governance and catalog tools. It is an operational complement.",
        },
        {
          title: "Medallion and ELT",
          href: "/help/platforms",
          text: "Adapts the product to modern contexts such as Databricks, Fabric, or Snowflake with a medallion, lakehouse, and ELT perspective.",
        },
      ],
      keyIdeas: [
        "MDM Lite covers an operational gap between raw data and consumable models: mappings, groups, and parameters with effective dates.",
        "It does not replace cataloging, governance, lineage, permissions, or data discovery; those still belong in Purview, Unity Catalog, or Collibra.",
        "Its value comes from simplicity: a small, understandable, operable layer for business or data stewardship without adopting an enterprise MDM platform.",
        "Technical integration relies on stable SQL view contracts, useful for classic SQL, Python, dbt, notebooks, or ELT pipelines.",
      ],
      audienceRoutes: [
        {
          audience: "Enablement and demos",
          title: "Start from the guided walkthrough",
          text: "Lets one person load the demo dataset, open each screen in sequence, and explain the product without prior context.",
          href: "/help/demo",
          cta: "Open guided demo",
        },
        {
          audience: "Business and sponsors",
          title: "Start from value and scope",
          text: "Ideal for explaining quickly what problem it solves, why it is not enterprise MDM, and who it actually competes with.",
          href: "/help/executive",
          cta: "Open executive FAQ",
        },
        {
          audience: "Architecture and governance",
          title: "Start from positioning",
          text: "Clarifies the relationship with Purview, Unity Catalog, Collibra, and other catalog, metadata, or governance pieces.",
          href: "/help/positioning",
          cta: "View positioning",
        },
        {
          audience: "Data engineering",
          title: "Start from technical integration",
          text: "Connects the product to ETL, ELT, medallion, dbt, notebooks, Databricks, Fabric, and Snowflake.",
          href: "/help/platforms",
          cta: "View medallion and ELT",
        },
      ],
      quickStart: [
        "Run a self-guided browser walkthrough: Guided demo.",
        "Understand the product in 3 minutes: Executive FAQ.",
        "Answer whether it competes with or complements Purview or Unity Catalog: Positioning.",
        "Show how it fits modern pipelines: Medallion and ELT.",
        "Understand screens, creation, editing, and day-to-day usage: Functional Guide.",
      ],
      heroEyebrow: "Help / Knowledge Center",
      title: "How to understand MDM Lite from business, data engineering, and architecture",
      description:
        "This section is no longer only screen help. It becomes a product explanation: what problem it solves, where it fits versus other tools, and how it integrates in classic DW environments and modern medallion, ELT, or lakehouse patterns.",
      productEyebrow: "Product",
      productTitle: "What MDM Lite is",
      productText:
        "A lightweight layer to manage simple master rules that technical processes need to consult all the time: effective mappings, groups, and parameters.",
      limitEyebrow: "Boundary",
      limitTitle: "What it is not",
      limitText:
        "It is not an enterprise catalog, not a cross-cutting governance platform, and not a full enterprise MDM suite. It is a simple complement that solves a very specific and frequent gap.",
      audienceEyebrow: "Quick entry",
      audienceTitle: "Choose by audience",
      shortcutEyebrow: "Shortcut",
      shortcutTitle: "If you have a meeting and little time",
      recommendedEyebrow: "Recommended reading",
      recommendedTitle: "Short portal tour",
      recommendedText:
        "Start with Executive FAQ to explain the product. Continue with Positioning if the conversation brings up catalog or governance. Finish with Medallion and ELT if the discussion moves into modern architecture.",
      executiveCta: "Executive FAQ",
      platformsCta: "Medallion and ELT",
      sectionEyebrow: "Section",
      openCta: "Open",
      ideasEyebrow: "Key ideas",
      ideasTitle: "Messages worth keeping clear",
      recommendationEyebrow: "Recommendation",
      recommendationTitle: "How to use this Help",
      recommendationText:
        "If the audience is functional, start with the Functional Guide. If it is architecture or governance, start with Positioning. If the audience is Databricks, Fabric, or Snowflake, start with Medallion and ELT.",
      executiveLink: "View executive FAQ",
      functionalLink: "View functional guide",
      positioningLink: "View positioning",
    },
    helpDemo: {
      eyebrow: "Help / Guided demo",
      title: "Run the product demo step by step from this page",
      description:
        "This page is designed so a user can keep it open and navigate the product alone. It explains what to click, what to say, and what to look for in each screen.",
      resetEyebrow: "Step 0",
      resetTitle: "Load the guided dataset",
      resetText:
        "Use the button below before starting the walkthrough. It resets operational data and loads a short scenario for CLIENT and PRODUCT with approved rules, pending approvals, and audit history.",
      goalEyebrow: "Demo goal",
      goalTitle: "What this walkthrough proves",
      goalBullets: [
        "The product centralizes small but critical business rules instead of leaving them in Excel or code.",
        "Business-friendly screens coexist with stable SQL contracts for data engineering consumption.",
        "The same dataset shows approved rules, pending approvals, and audit traceability.",
      ],
      doTitle: "What to do",
      lookTitle: "What to look for",
      storyEyebrow: "Narrative",
      storyTitle: "Story you can tell while navigating",
      storyBullets: [
        "CLIENT shows how several source names converge into a canonical customer used by downstream processes.",
        "PRODUCT shows the same pattern for SKUs, product families, and operational parameters.",
        "Approvals and Audit make the product credible because rules do not appear magically; they move through a simple governed flow.",
      ],
      sqlEyebrow: "Technical close",
      sqlTitle: "Optional ending for Fabric, Databricks, or Snowflake audiences",
      sqlText: "If the audience is technical, finish by showing that downstream processes only need the active views.",
      sqlExample: `select entity_type_code, source_value, target_value
from vw_mdm_mapping_rule_active
order by entity_type_code, source_value;

select entity_type_code, member_value, group_value
from vw_mdm_group_rule_active
order by entity_type_code, member_value;

select parameter_key, parameter_value, parameter_scope_type, parameter_scope_value
from vw_mdm_parameter_active
where domain = 'demo_training'
order by parameter_scope_type, parameter_scope_value;`,
      secondaryCta: "Open approvals",
      steps: [
        {
          kicker: "Step 1",
          title: "Open Mappings and show canonicalization",
          href: "/mappings",
          cta: "Open mappings",
          text: "Start with the most intuitive screen: two or more source names end in one canonical value.",
          doItems: [
            "Open the Mappings page.",
            "Filter by ACME or COFFEE if you want a shorter view.",
            "Point out CLIENT and PRODUCT examples side by side.",
          ],
          lookFor: [
            "ACME S.A. and ACME SA both land on ACME_RETAIL.",
            "CAF 1KG and CAFE MOLIDO 1KG both land on SKU_COFFEE_1KG.",
          ],
        },
        {
          kicker: "Step 2",
          title: "Open Groups and show business segmentation",
          href: "/groups",
          cta: "Open groups",
          text: "After canonicalization, the product can place customers or products into business-oriented groups.",
          doItems: [
            "Open the Groups page.",
            "Locate ACME_RETAIL and SKU_COFFEE_1KG.",
            "Explain that grouping feeds reporting, planning, and pricing logic.",
          ],
          lookFor: [
            "ACME_RETAIL belongs to MODERN_TRADE.",
            "SKU_COFFEE_1KG belongs to HOT_BEVERAGES.",
          ],
        },
        {
          kicker: "Step 3",
          title: "Open Parameters and show operational rules",
          href: "/parameters",
          cta: "Open parameters",
          text: "This screen shows values that processes use directly, such as commercial factors or minimum margins.",
          doItems: [
            "Open the Parameters page.",
            "Filter by demo_training or PVP_FACTOR.",
            "Compare a CLIENT-scoped parameter with a PRODUCT-scoped parameter.",
          ],
          lookFor: [
            "ACME_RETAIL has a PVP_FACTOR.",
            "SKU_COFFEE_1KG has a MIN_MARGIN.",
          ],
        },
        {
          kicker: "Step 4",
          title: "Open Approvals and show pending work",
          href: "/approvals",
          cta: "Open approvals",
          text: "This is where the product stops being a passive table browser and starts looking operational.",
          doItems: [
            "Open the Approvals page.",
            "Show the pending mapping, group, and parameter created by the demo scenario.",
            "Explain that these proposals do not affect active views until approval.",
          ],
          lookFor: [
            "A pending ACME mapping proposal.",
            "A pending PREMIUM_BEVERAGES product group.",
            "A pending future PVP_FACTOR for ACME_RETAIL.",
          ],
        },
        {
          kicker: "Step 5",
          title: "Open Audit and show traceability",
          href: "/audit",
          cta: "Open audit",
          text: "Close the walkthrough by proving that every seeded rule has a visible operational history.",
          doItems: [
            "Open the Audit page.",
            "Filter by mdm_mapping_rule or mdm_parameter if you want a tighter story.",
            "Show create and approve or submit events.",
          ],
          lookFor: [
            "Create plus approve events for approved demo records.",
            "Create plus submit events for pending demo records.",
          ],
        },
      ],
    },
    helpExecutive: {
      faqItems: [
        {
          question: "What problem does MDM Lite solve?",
          answer:
            "It solves a very common operational problem: small but critical rules often end up scattered across Excel files, loose tables, and repeated code. It centralizes mappings, groups, and parameters with effective dates so pipelines consume a stable version.",
        },
        {
          question: "Is it enterprise MDM?",
          answer:
            "No. It is not trying to cover golden record, survivorship, complex workflow, extended data stewardship, or company-wide governance. It covers a narrower use case: reference data and operational rules ready for ETL or ELT consumption.",
        },
        {
          question: "Does it compete with Purview or Unity Catalog?",
          answer:
            "Not directly. Purview, Unity Catalog, and similar tools govern the data ecosystem. MDM Lite manages the concrete rules that this ecosystem needs when transforming business data.",
        },
        {
          question: "Who does it really compete with?",
          answer:
            "It competes with three things: MDM platforms that are too large for the problem, lightweight but fragmented RDM solutions, and the most common real alternative, which is shared Excel plus auxiliary tables without a stable contract.",
        },
        {
          question: "Why is simplicity an advantage?",
          answer:
            "Because it reduces adoption time, specialist dependency, and friction with data engineering. When the problem is focused, a bounded solution creates value sooner and with much lower operational cost.",
        },
        {
          question: "Where does it fit in modern architectures?",
          answer:
            "It fits in classic ETL, ELT, medallion, and lakehouse. It is typically used in the intermediate layer where values are normalized and rules are applied before publishing curated datasets or business marts.",
        },
      ],
      executiveMessages: [
        "MDM Lite is not trying to govern all data; it is trying to organize the rules pipelines use every day.",
        "Its value appears when a team needs operational consistency without deploying a full enterprise platform.",
        "The technical contract is expressed in simple SQL views, suitable for SQL, dbt, notebooks, Python, or modern pipelines.",
      ],
      eyebrow: "Help / Executive FAQ",
      title: "Executive questions to explain what MDM Lite is and where it fits",
      description:
        "This page is meant for short conversations with sponsors, architecture, governance, or technical leadership. It summarizes the product without unnecessary jargon.",
      summaryEyebrow: "Summary",
      summaryTitle: "Three ideas to open the conversation",
      shortEyebrow: "Short line",
      shortTitle: "How to summarize it in a meeting",
      shortText:
        "MDM Lite is an operational layer for simple master rules. It does not replace cataloging or governance; it complements those capabilities with mappings, groups, and parameters ready for technical consumption.",
      questionEyebrow: "Question",
    },
    helpFunctional: {
      contractViews: [
        {
          name: "vw_mdm_mapping_rule_active",
          purpose: "Read contract used to map source values to a canonical value before consolidation or loading.",
        },
        {
          name: "vw_mdm_group_rule_active",
          purpose: "Read contract used to group already mapped values into a commercial or analytical family.",
        },
        {
          name: "vw_mdm_parameter_active",
          purpose: "Read contract used to apply factors, flags, or settings by domain and scope.",
        },
      ],
      exampleRows: [
        {
          stage: "Raw input",
          clientSource: "ALDI PORTUGAL",
          groupSource: "ALDI PORTUGAL",
          factorSource: "unresolved",
          priceSource: "100.00",
          outcome: "It is not ready for reporting yet because it still depends on the source name as received.",
        },
        {
          stage: "After mapping",
          clientSource: "ALDI",
          groupSource: "ALDI",
          factorSource: "unresolved",
          priceSource: "100.00",
          outcome: "The customer is now normalized to the canonical name expected by the analytical model.",
        },
        {
          stage: "After grouping",
          clientSource: "ALDI",
          groupSource: "ALDI GROUP",
          factorSource: "unresolved",
          priceSource: "100.00",
          outcome: "It can now be consolidated in dashboards by commercial group and not only by individual customer.",
        },
        {
          stage: "After parameter",
          clientSource: "ALDI",
          groupSource: "ALDI GROUP",
          factorSource: "1.08",
          priceSource: "108.00",
          outcome: "The ETL applies the current factor and leaves the record ready for analytics or downstream use.",
        },
      ],
      optionCards: [
        {
          title: "Mappings",
          href: "/mappings",
          whatItIs: "Maps a source value to a canonical or target value to avoid hardcoding in processes and reports.",
          administration:
            "It is created when an external code or description does not match the internal standard. The admin defines when the rule becomes valid and what the mapped value is.",
          fields: ["Entity", "Source key", "Source value", "Target value", "Effective date"],
          realUse:
            "In a sales ETL, if the ERP sends 'ALDI PORTUGAL' and the analytical model expects 'ALDI', the mapping resolves the translation before loading the fact table.",
        },
        {
          title: "Groups",
          href: "/groups",
          whatItIs: "Groups multiple operational values into a common commercial or analytical family.",
          administration:
            "It is used when several customers, materials, or codes must be consolidated under the same business view. The admin defines member, group, and effective date.",
          fields: ["Member", "Group", "Group label", "Rule set", "Effective date"],
          realUse:
            "In a customer ETL, 'EROSKI S.COOP.' and other variants can end up in the 'EROSKY' group for regional reporting or commercial agreements.",
        },
        {
          title: "Parameters",
          href: "/parameters",
          whatItIs: "Stores business configuration values that change over time or by context, without touching code.",
          administration:
            "It is maintained when a rule depends on a factor, percentage, or flag by customer, channel, country, or domain. The admin defines key, value, scope, and effective date.",
          fields: ["Key", "Value", "Domain", "Scope type", "Scope value", "Effective date"],
          realUse:
            "In a pricing ETL, a parameter like 'PVP_FACTOR' may be 1.09 for MARJANE and 0.97 for PRIMOR, and the process reads it while transforming prices.",
        },
        {
          title: "Import",
          href: "/imports",
          whatItIs: "Allows loading demo batches or manual csv/xlsx files to populate rules without entering them one by one.",
          administration:
            "It is used when a business file arrives or when a base set must be restored. The admin selects the data type, uploads the file, and reviews the result.",
          fields: ["Load type", "File", "Result", "Inserted or updated count"],
          realUse:
            "In an operational ETL process, business delivers an Excel file with new mappings and the admin imports it before the nightly run.",
        },
      ],
      etlSteps: [
        "The source system delivers raw data with non-normalized codes and descriptions.",
        "The ETL extracts that data and queries MDM Lite for current mappings, groups, and parameters.",
        "During transformation, the ETL replaces source values, consolidates groups, and applies scoped parameters.",
        "The normalized result is loaded into analytical tables, marts, or reporting models.",
        "If a new value appears that is not covered yet, the admin loads it into MDM Lite and the next run resolves it without code changes.",
      ],
      operatingRules: [
        "Simple manual entry: useful for punctual fixes or controlled tests.",
        "File import: useful for volume, initial onboarding, or periodic maintenance.",
        "Effective date: each rule should have a date from which it applies; this prevents uncontrolled overwriting of history.",
        "Technical consumption: ETL should always read from active views to avoid depending on internal tables.",
        "Controlled change: when a rule changes, it is better to create a new effective record than edit past history.",
      ],
      eyebrow: "Help / Functional Guide",
      title: "What each option does and how to use it in a real ETL scenario",
      description:
        "This guide keeps the original focus: explain the functional meaning of each module, what data is loaded, how it is administered, and how it is consumed from classic technical processes.",
      optionEyebrow: "Menu option",
      openOption: "Open option",
      whatItIsTitle: "What it is",
      administrationTitle: "How it is managed",
      fieldsTitle: "What goes in",
      realUseTitle: "Real ETL usage",
      practicalEyebrow: "Practical flow",
      practicalTitle: "How it would enter a real ETL",
      practicalText:
        "This remains the baseline MVP flow when consumed from a classic DW or a traditional batch process.",
      exampleEyebrow: "Detailed example",
      exampleTitle: "Before and after in an ETL run",
      tableHeaders: [
        "Stage",
        "Canonical customer",
        "Commercial group",
        "Applied factor",
        "Resulting price",
        "Functional interpretation",
      ],
      contractEyebrow: "Technical contract",
      contractTitle: "Views a process should consume",
      contractText: "The recommended contract for v0.1 is based on active views rather than internal tables.",
      sqlEyebrow: "Usage from SQL",
      sqlTitle: "Relational query",
      pythonEyebrow: "Usage from Python",
      pythonTitle: "Batch script or notebook",
      dbtEyebrow: "Usage from dbt",
      dbtTitle: "Enriched model",
      practicesEyebrow: "Best practices",
      practicesTitle: "How to operate it well",
      nextEyebrow: "Next reading",
      nextTitle: "For modern data platform audiences",
      nextText:
        "If the conversation moves toward Databricks, Fabric, Snowflake, medallion, or ELT, the dedicated page for those patterns is the best continuation.",
      platformsCta: "View medallion and ELT",
      positioningCta: "View positioning",
    },
    helpPositioning: {
      complementRows: [
        {
          tool: "Purview / Microsoft Purview",
          strength: "Catalog, lineage, governance, classification, and cross-platform visibility.",
          gap: "It is not designed to operate day-to-day mappings, groups, or small business parameters.",
          mdmLiteRole:
            "MDM Lite lives below that level: it manages the concrete rules an ETL needs to query during transformation.",
        },
        {
          tool: "Unity Catalog",
          strength: "Data governance, permissions, cataloging, and control over Databricks assets.",
          gap: "By itself it does not solve the operational maintenance of functional rules such as canonical names, commercial groups, or customer factors.",
          mdmLiteRole:
            "MDM Lite can publish governed tables or views inside the broader ecosystem governed by Unity Catalog.",
        },
        {
          tool: "Collibra / Alation / similar catalogs",
          strength: "Business definitions, ownership, discovery, and governance operating model.",
          gap: "They are usually more oriented to metadata and governance than to a simple rules operation with create, edit, and immediate pipeline integration.",
          mdmLiteRole:
            "MDM Lite covers the operational gap between conceptual definition and the technical application of a rule.",
        },
      ],
      competitorRows: [
        {
          type: "Classic enterprise MDM",
          examples: "Informatica MDM, Reltio, Semarchy xDM, Profisee, SAP MDG",
          fit: "They compete in the broader master data management space with workflow, golden record, survivorship, and advanced governance.",
          difference:
            "MDM Lite does not try to cover that width. It wins when the real problem is smaller, more focused, and oriented to fast technical consumption.",
        },
        {
          type: "Specific reference data manager",
          examples: "RDM solutions or lightweight implementations built on tables and APIs",
          fit: "They compete more directly when the goal is to maintain operational catalogs and simple rules.",
          difference:
            "MDM Lite aims to be clearer, more explainable, and more ETL-ready than a dispersed collection of custom tables.",
        },
        {
          type: "Homegrown implementation",
          examples: "Shared Excel, versioned CSVs, loose tables in a utility schema",
          fit: "This is the most common real alternative in small or medium teams.",
          difference:
            "This is exactly where simplicity matters most: MDM Lite organizes that chaos with a minimal UI, effective dates, and stable read contracts.",
        },
      ],
      simplicityPoints: [
        "Lower adoption cost: an admin can understand it and use it quickly.",
        "Lower technical complexity: SQL views and simple forms instead of heavy platforms.",
        "Lower friction with data engineering: technical consumption is obvious and direct.",
        "Better fit for teams that still do not justify enterprise MDM.",
        "High value for small but recurrent gaps: mappings, groups, and functional parameters.",
      ],
      positioningMessages: [
        "We do not compete with catalog and governance tools; we complement them.",
        "We do not replace lineage, permissions, classification, ownership, or discovery.",
        "We truly compete against solutions that are too heavy or against the chaos of Excel plus loose tables.",
        "The value proposition is not functional breadth, but speed, clarity, and operational simplicity.",
      ],
      eyebrow: "Help / Positioning",
      title: "How it positions itself against Purview, Unity Catalog, and other tools",
      description:
        "This page makes it explicit where MDM Lite fits so it is not read as a competitor to governance or catalog platforms.",
      centralEyebrow: "Core message",
      centralTitle: "Complement, not replacement",
      readingEyebrow: "Recommended framing",
      readingTitle: "How to explain it quickly",
      readingText:
        "Purview, Unity Catalog, or Collibra govern the data ecosystem. MDM Lite operates the small but critical rules that ETL actually needs to apply.",
      visualEyebrow: "Visual map",
      visualTitle: "Where MDM Lite sits",
      governanceKicker: "Governance and catalog",
      governanceText: "Discovery, ownership, permissions, lineage, and cross-platform visibility.",
      operationsKicker: "Rules operations",
      operationsText: "Current mappings, groups, and parameters used by real transformations.",
      consumptionKicker: "Consumption",
      consumptionText: "Consistent rule application in ETL, ELT, marts, and semantic layers.",
      complementEyebrow: "Comparison",
      complementTitle: "What it complements",
      complementHeaders: ["Tool", "Primary value", "Typical gap", "Role of MDM Lite"],
      competitorsEyebrow: "Competition",
      competitorsTitle: "Who we actually compete with",
      competitorHeaders: ["Space", "Examples", "Where it competes", "MDM Lite difference"],
      valueEyebrow: "Value",
      valueTitle: "Why simplicity matters",
      shortEyebrow: "Short line",
      shortTitle: "How to summarize the fit",
      shortText:
        "Purview or Unity Catalog tell you what data exists, who governs it, and how it is controlled. MDM Lite helps you decide how to transform specific business values so that data can be consumed consistently.",
    },
    helpPlatforms: {
      medallionRows: [
        {
          layer: "Bronze / Raw",
          role: "Preserve data as it arrives from the source.",
          mdmUsage: "Typically MDM Lite does not modify Bronze. At most, it helps detect new values that are not mapped yet.",
        },
        {
          layer: "Silver / Cleansed",
          role: "Normalize, enrich, and make data usable for downstream models.",
          mdmUsage: "This is the natural place to apply mappings, groups, and parameters. This is where MDM Lite adds the most value.",
        },
        {
          layer: "Gold / Business-ready",
          role: "Publish curated datasets for BI, semantic layers, or business consumption.",
          mdmUsage: "Gold receives already normalized data from Silver. MDM Lite usually does not operate directly here, but its effect is very visible in dashboards and metrics.",
        },
      ],
      platformPatterns: [
        {
          platform: "Databricks",
          pattern: "Curated tables or views in Unity Catalog, notebooks, or jobs that read rules from PostgreSQL or a controlled replica.",
        },
        {
          platform: "Microsoft Fabric",
          pattern: "Dataflows, notebooks, or pipelines that query active views to enrich Silver and Gold layers.",
        },
        {
          platform: "Snowflake",
          pattern: "ELT in SQL or dbt consuming active views for normalization before marts or semantic models.",
        },
      ],
      eltMessages: [
        "In ELT, the transformation lives inside the analytical engine, but it still needs a stable rule source.",
        "MDM Lite does not impose a runtime: it can feed SQL, dbt, notebooks, stored procedures, or orchestrated pipelines.",
        "The correct pattern is to expose simple rules as queryable data, not repeated code in every model.",
        "In modern lakehouse and warehouse environments, the problem still exists: inconsistent names, commercial groups, and functional factors keep appearing.",
      ],
      recommendedPatterns: [
        "Treat MDM Lite as an external and stable reference dataset.",
        "Apply mappings first, then groups, and parameters last.",
        "Resolve transformations in Silver or the equivalent intermediate layer.",
        "Publish Gold or marts with canonical data and rules already applied.",
        "Keep the technical contract in views to avoid coupling pipelines to internal tables.",
      ],
      antiPatterns: [
        "Apply different rules in each notebook or model without a common source.",
        "Maintain mappings in loose spreadsheets outside the controlled pipeline.",
        "Use Gold as the place to correct names that should have been resolved earlier.",
        "Embed mapping lists in scattered Python, SQL, or YAML code.",
        "Couple to internal tables instead of active views.",
      ],
      eyebrow: "Help / Medallion and ELT",
      title: "How it fits in Databricks, Fabric, Snowflake, and modern architectures",
      description:
        "This page translates the MVP into more current language: medallion, ELT, lakehouse, semantic layer, and modern pipelines.",
      centralEyebrow: "Core message",
      centralTitle: "Medallion does not remove the need for master rules",
      centralText:
        "Even when the stack changes, inconsistent names, external codes, business groupings, and time-sensitive parameters keep arriving.",
      eltEyebrow: "ELT",
      eltTitle: "What changes versus classic ETL",
      visualEyebrow: "Visual map",
      visualTitle: "Typical placement in a medallion architecture",
      bronzeText: "Nearly untouched input from ERP, CRM, files, or APIs.",
      silverText: "Mapping, grouping, and parameters before publishing curated datasets.",
      goldText: "Dashboards, marts, semantic models, and analytics on canonical values.",
      medallionEyebrow: "Medallion",
      medallionTitle: "Which layer contains the value of MDM Lite",
      medallionHeaders: ["Layer", "Role", "Recommended MDM Lite usage"],
      platformsEyebrow: "Platforms",
      platformsTitle: "Typical patterns by ecosystem",
      platformHeaders: ["Platform", "Integration pattern"],
      recommendedEyebrow: "Recommended pattern",
      recommendedTitle: "How to integrate it well",
      antiEyebrow: "Anti-patterns",
      antiTitle: "What to avoid",
      quickEyebrow: "Quick read",
      quickTitle: "Modern pattern summary",
      rulesKicker: "Rules source",
      rulesText: "PostgreSQL with active views as a stable contract decoupled from internal tables.",
      engineKicker: "Transformation engine",
      engineText: "Centralized rule application in the intermediate layer.",
      outputKicker: "Output",
      outputText: "Uniform consumption on top of already normalized data.",
    },
  },
  es: {
    header: {
      navLabel: "Principal",
      links: [
        { href: "/", label: "Inicio" },
        { href: "/mappings", label: "Equivalencias" },
        { href: "/groups", label: "Agrupaciones" },
        { href: "/parameters", label: "Parametros" },
        { href: "/approvals", label: "Aprobaciones" },
        { href: "/audit", label: "Auditoria" },
        { href: "/imports", label: "Importacion" },
        { href: "/help", label: "Ayuda" },
        { href: "/api/health/db", label: "DB Health" },
      ],
      themeToggle: "Cambiar tema de color",
      languageToggle: "Cambiar idioma",
      lightTheme: "Claro",
      darkTheme: "Oscuro",
      english: "EN",
      spanish: "ES",
      logout: "Salir",
    },
    home: {
      eyebrow: "MDM Lite / Reference Data Manager",
      title: "Base inicial del proyecto para gobernar reglas de negocio sin hardcode.",
      description:
        "El repositorio ya esta organizado con documentacion, esquema SQL, dataset demo y scaffold de aplicacion para arrancar el MVP sobre PostgreSQL estandar.",
      primaryCta: "Ver equivalencias",
      secondaryCta: "Ver parametros",
      panelTitle: "Estado del arranque",
      panelItems: [
        "Documentacion organizada en docs/",
        "Dataset demo ubicado en data/demo/",
        "Esquema inicial en db/schema/",
        "Stack base definido para Next.js + TypeScript",
        "Puerto local web configurado en",
        "Healthcheck DB disponible en /api/health/db",
      ],
      statLabels: {
        mappings: "equivalencias",
        groups: "agrupaciones",
        parameters: "parametros",
      },
      cards: [
        {
          title: "Datos Maestros",
          text: "Equivalencias, agrupaciones y parametros con vigencia y auditoria.",
        },
        {
          title: "Importacion Demo",
          text: "Carga por CSV o XLSX con revision previa y correccion manual simple.",
        },
        {
          title: "Consumo Tecnico",
          text: "Contrato inicial por vistas SQL, preparado para API o MCP en fases futuras.",
        },
        {
          title: "Operacion Simple",
          text: "MVP monoempresa con un admin inicial y flujo liviano de aprobacion.",
        },
      ],
      demoReset: {
        eyebrow: "Demo Guiada",
        title: "Resetear y cargar el escenario de capacitacion",
        description:
          "Borra las reglas operativas actuales y repone una historia corta y explicable para CLIENT y PRODUCT, con aprobados, pendientes y auditoria.",
        cta: "Cargar demo guiada",
        processing: "Cargando demo...",
        confirm:
          "Esto va a borrar mappings, groups, parameters, imports y auditoria operativa actuales, y luego va a cargar el escenario demo guiado. Queres continuar?",
        helpCta: "Abrir guia funcional",
        note: "Conviene usarlo antes de una demo en vivo, una capacitacion o una primera presentacion del producto.",
        success: "Demo guiada cargada correctamente.",
        error: "No se pudo cargar la demo guiada",
      },
    },
    mappingsPage: {
      eyebrow: "Vista Operativa",
      title: "Equivalencias activas",
      description:
        "Reglas aprobadas, activas y vigentes listas para consumo tecnico. Esta vista ya lee desde la base remota de Supabase.",
      recordsLabel: "registros",
      sourceLabel: "Fuente: vw_mdm_mapping_rule_active",
      filterPlaceholder: "Buscar por origen, destino o rule set",
    },
    groupsPage: {
      eyebrow: "Vista Operativa",
      title: "Agrupaciones activas",
      description: "Reglas de agrupacion aprobadas, activas y vigentes listas para reporting o consolidacion.",
      recordsLabel: "registros",
      sourceLabel: "Fuente: vw_mdm_group_rule_active",
      filterPlaceholder: "Buscar por miembro, grupo o rule set",
    },
    parametersPage: {
      eyebrow: "Vista Operativa",
      title: "Parametros activos",
      description:
        "Parametros vigentes expuestos con alcance funcional simple. El demo actual refleja factores PVP por cliente.",
      recordsLabel: "registros",
      sourceLabel: "Fuente: vw_mdm_parameter_active",
      filterPlaceholder: "Buscar por clave, dominio o alcance",
    },
    importsPage: {
      eyebrow: "Operacion",
      title: "Importacion de datos",
      description:
        "Consola inicial para reimportar el dataset demo del proyecto o cargar archivos manuales csv/xlsx hacia equivalencias, agrupaciones y parametros.",
    },
    forms: {
      filterSubmit: "Filtrar",
      mappingCreate: {
        eyebrow: "Alta Manual",
        title: "Nueva equivalencia",
        description: "Formulario liviano para cargar una homologacion sin pasar por importacion de archivo.",
        sourceValueLabel: "Valor origen",
        sourceValuePlaceholder: "ALDI SAN ISIDRO SUPERMERCADOS, S.L.",
        targetValueLabel: "Valor destino",
        targetValuePlaceholder: "ALDI SUPERMERCADOS",
        validFromLabel: "Vigente desde",
        commentsLabel: "Comentario",
        commentsPlaceholder: "Carga manual desde UI",
        submitting: "Guardando...",
        submit: "Crear equivalencia",
        success: "Equivalencia creada correctamente.",
      },
      mappingTable: {
        empty: "No hay equivalencias activas para el filtro actual.",
        headers: ["Entidad", "Clave origen", "Valor origen", "Valor destino", "Rule set", "Vigencia", "Accion"],
        edit: "Editar",
        close: "Cerrar",
        sourceValueLabel: "Valor origen",
        targetValueLabel: "Valor destino",
        validFromLabel: "Vigente desde",
        commentsLabel: "Comentario",
        commentsPlaceholder: "Actualizacion manual desde UI",
        saving: "Guardando...",
        save: "Guardar cambios",
        cancel: "Cancelar",
        success: "Equivalencia actualizada.",
      },
      groupCreate: {
        eyebrow: "Alta Manual",
        title: "Nueva agrupacion",
        description: "Formulario liviano para cargar una agrupacion comercial sin depender de importacion.",
        memberLabel: "Miembro",
        memberPlaceholder: "EROSKI S.COOP.",
        groupLabel: "Grupo",
        groupPlaceholder: "EROSKY",
        validFromLabel: "Vigente desde",
        commentsLabel: "Comentario",
        commentsPlaceholder: "Carga manual desde UI",
        submitting: "Guardando...",
        submit: "Crear agrupacion",
        success: "Agrupacion creada correctamente.",
      },
      groupTable: {
        empty: "No hay agrupaciones activas para el filtro actual.",
        headers: ["Entidad", "Miembro", "Grupo", "Etiqueta", "Rule set", "Vigencia", "Accion"],
        edit: "Editar",
        close: "Cerrar",
        memberLabel: "Miembro",
        groupLabel: "Grupo",
        validFromLabel: "Vigente desde",
        commentsLabel: "Comentario",
        commentsPlaceholder: "Actualizacion manual desde UI",
        saving: "Guardando...",
        save: "Guardar cambios",
        cancel: "Cancelar",
        success: "Agrupacion actualizada.",
      },
      parameterCreate: {
        eyebrow: "Alta Manual",
        title: "Nuevo parametro",
        description: "Formulario liviano para cargar parametros activos con alcance simple por cliente u otro contexto.",
        parameterKeyLabel: "Clave",
        parameterValueLabel: "Valor",
        parameterValuePlaceholder: "1.05",
        domainLabel: "Dominio",
        scopeTypeLabel: "Tipo de alcance",
        scopeValueLabel: "Valor de alcance",
        scopeValuePlaceholder: "MARJANE",
        validFromLabel: "Vigente desde",
        commentsLabel: "Comentario",
        commentsPlaceholder: "Carga manual desde UI",
        submitting: "Guardando...",
        submit: "Crear parametro",
        success: "Parametro creado correctamente.",
      },
      parameterTable: {
        empty: "No hay parametros activos para el filtro actual.",
        headers: ["Clave", "Valor", "Tipo", "Dominio", "Alcance", "Vigencia", "Accion"],
        edit: "Editar",
        close: "Cerrar",
        global: "GLOBAL",
        parameterKeyLabel: "Clave",
        parameterValueLabel: "Valor",
        domainLabel: "Dominio",
        scopeTypeLabel: "Tipo de alcance",
        scopeValueLabel: "Valor de alcance",
        validFromLabel: "Vigente desde",
        commentsLabel: "Comentario",
        commentsPlaceholder: "Actualizacion manual desde UI",
        saving: "Guardando...",
        save: "Guardar cambios",
        cancel: "Cancelar",
        success: "Parametro actualizado.",
      },
      importsConsole: {
        demoEyebrow: "Dataset Demo",
        demoTitle: "Reimportar workbook del proyecto",
        demoDescription:
          "Ejecuta la carga del Excel demo guardado en data/demo/ para reponer equivalencias, agrupaciones y parametros base.",
        demoCta: "Importar demo del servidor",
        uploadEyebrow: "Carga Manual",
        uploadTitle: "Subir CSV o XLSX",
        uploadDescription: "Importa un archivo para equivalencias, agrupaciones o parametros. Se usa la primera hoja del archivo.",
        targetLabel: "Tipo de importacion",
        targetOptions: {
          mappings: "Equivalencias",
          groups: "Agrupaciones",
          parameters: "Parametros",
        },
        fileLabel: "Archivo",
        uploadCta: "Subir e importar",
        processing: "Procesando...",
        resultEyebrow: "Resultado",
        resultTitle: "Estado de la ultima ejecucion",
        noResult: "No hay ejecuciones recientes en esta sesion.",
        success: "Importacion completada correctamente.",
        error: "La importacion fallo.",
      },
    },
    helpNav: {
      ariaLabel: "Secciones Help",
      links: {
        overview: "Resumen",
        demo: "Demo guiada",
        executive: "FAQ ejecutiva",
        functional: "Guia funcional",
        positioning: "Posicionamiento",
        platforms: "Medallion y ELT",
      },
    },
    helpOverview: {
      sections: [
        {
          title: "Demo guiada",
          href: "/help/demo",
          text: "Recorrido paso a paso para cargar la demo curada y explicar el producto solo desde el navegador, incluyendo que hacer y que mirar.",
        },
        {
          title: "FAQ ejecutiva",
          href: "/help/executive",
          text: "Resume en lenguaje ejecutivo que problema resuelve MDM Lite, con quien compite de verdad y por que no reemplaza Purview, Unity Catalog o catalogos corporativos.",
        },
        {
          title: "Guia funcional",
          href: "/help/functional",
          text: "Explica que hace cada modulo, como se carga la informacion y como entra MDM Lite en una corrida ETL tradicional.",
        },
        {
          title: "Posicionamiento",
          href: "/help/positioning",
          text: "Aclara que MDM Lite no compite con Purview, Unity Catalog u otras herramientas de catalogo y gobierno. Se posiciona como complemento operativo.",
        },
        {
          title: "Medallion y ELT",
          href: "/help/platforms",
          text: "Baja el uso del producto a contextos modernos como Databricks, Fabric o Snowflake con enfoque medallion, lakehouse y ELT.",
        },
      ],
      keyIdeas: [
        "MDM Lite cubre un hueco operativo entre el dato crudo y el modelo consumible: homologaciones, agrupaciones y parametros con vigencia.",
        "No reemplaza catalogo, gobierno, lineage, permisos ni descubrimiento de datos; eso sigue viviendo en plataformas como Purview, Unity Catalog o Collibra.",
        "Su valor esta en la simplicidad: una capa pequena, entendible y operable por negocio o data stewardship sin abrir una plataforma MDM enterprise.",
        "La integracion tecnica se apoya en contratos estables por vistas SQL, utiles para SQL clasico, Python, dbt, notebooks o pipelines ELT.",
      ],
      audienceRoutes: [
        {
          audience: "Capacitacion y demos",
          title: "Entrar por el recorrido guiado",
          text: "Permite que una persona cargue el dataset demo, abra cada pantalla en secuencia y explique el producto sin contexto previo.",
          href: "/help/demo",
          cta: "Abrir demo guiada",
        },
        {
          audience: "Negocio y sponsors",
          title: "Entrar por valor y alcance",
          text: "Ideal para explicar rapido que problema resuelve, por que no es un MDM enterprise y con quien compite de verdad.",
          href: "/help/executive",
          cta: "Abrir FAQ ejecutiva",
        },
        {
          audience: "Arquitectura y gobierno",
          title: "Entrar por posicionamiento",
          text: "Aclara la relacion con Purview, Unity Catalog, Collibra y otras piezas de catalogo, metadata o gobierno.",
          href: "/help/positioning",
          cta: "Ver posicionamiento",
        },
        {
          audience: "Data engineering",
          title: "Entrar por integracion tecnica",
          text: "Baja el producto a ETL, ELT, medallion, dbt, notebooks, Databricks, Fabric y Snowflake.",
          href: "/help/platforms",
          cta: "Ver medallion y ELT",
        },
      ],
      quickStart: [
        "Hacer una demo autoguiada desde el navegador: Demo guiada.",
        "Entender el producto en 3 minutos: FAQ ejecutiva.",
        "Responder si compite o complementa a Purview o Unity Catalog: Posicionamiento.",
        "Mostrar encaje en pipelines modernos: Medallion y ELT.",
        "Entender pantallas, altas, ediciones y uso funcional: Guia funcional.",
      ],
      heroEyebrow: "Help / Centro de Conocimiento",
      title: "Como entender MDM Lite desde negocio, data engineering y arquitectura",
      description:
        "Esta seccion ya no es solo una ayuda de pantalla. Pasa a ser una explicacion de producto: que problema resuelve, donde encaja frente a otras herramientas y como se integra en entornos clasicos de DW y en modelos modernos tipo medallion, ELT o lakehouse.",
      productEyebrow: "Producto",
      productTitle: "Que es MDM Lite",
      productText:
        "Una capa liviana para administrar reglas maestras simples que los procesos tecnicos necesitan consultar todo el tiempo: equivalencias, agrupaciones y parametros vigentes.",
      limitEyebrow: "Limite",
      limitTitle: "Que no es",
      limitText:
        "No es un catalogo corporativo, no es una plataforma de gobierno transversal y no es un MDM enterprise completo. Es un complemento simple que resuelve un hueco muy concreto y muy frecuente.",
      audienceEyebrow: "Entrada rapida",
      audienceTitle: "Elegir segun la audiencia",
      shortcutEyebrow: "Atajo",
      shortcutTitle: "Si tienes una reunion y poco tiempo",
      recommendedEyebrow: "Lectura recomendada",
      recommendedTitle: "Recorrido corto del portal",
      recommendedText:
        "Empieza por FAQ ejecutiva para explicar el producto. Sigue por Posicionamiento si aparece la comparacion con catalogo o gobierno. Cierra con Medallion y ELT si la conversacion entra en arquitectura moderna.",
      executiveCta: "FAQ ejecutiva",
      platformsCta: "Medallion y ELT",
      sectionEyebrow: "Seccion",
      openCta: "Abrir",
      ideasEyebrow: "Ideas clave",
      ideasTitle: "Mensajes que conviene dejar claros",
      recommendationEyebrow: "Recomendacion",
      recommendationTitle: "Como usar esta Help",
      recommendationText:
        "Si la audiencia es funcional, empieza por Guia funcional. Si es arquitectura o gobierno, empieza por Posicionamiento. Si la audiencia es Databricks, Fabric o Snowflake, empieza por Medallion y ELT.",
      executiveLink: "Ver FAQ ejecutiva",
      functionalLink: "Ver guia funcional",
      positioningLink: "Ver posicionamiento",
    },
    helpDemo: {
      eyebrow: "Help / Demo guiada",
      title: "Correr la demo del producto paso a paso desde esta pagina",
      description:
        "Esta pagina esta pensada para que una persona la deje abierta y navegue el producto sola. Explica que tocar, que decir y que deberia observar en cada pantalla.",
      resetEyebrow: "Paso 0",
      resetTitle: "Cargar el dataset guiado",
      resetText:
        "Usa el boton de abajo antes de empezar. Resetea los datos operativos y carga un escenario corto para CLIENT y PRODUCT con reglas aprobadas, pendientes y auditoria.",
      goalEyebrow: "Objetivo",
      goalTitle: "Que demuestra este recorrido",
      goalBullets: [
        "El producto centraliza reglas de negocio chicas pero criticas en vez de dejarlas en Excel o codigo.",
        "Las pantallas amigables para negocio conviven con contratos SQL estables para consumo tecnico.",
        "El mismo dataset permite mostrar aprobados, pendientes y trazabilidad operativa.",
      ],
      doTitle: "Que hacer",
      lookTitle: "Que mirar",
      storyEyebrow: "Narrativa",
      storyTitle: "Historia que puedes contar mientras navegas",
      storyBullets: [
        "CLIENT muestra como varios nombres de origen convergen en un cliente canonico que luego usan los procesos downstream.",
        "PRODUCT muestra el mismo patron para SKU, familias de producto y parametros operativos.",
        "Approvals y Audit vuelven creible el producto porque las reglas no aparecen por magia: pasan por un flujo simple y gobernado.",
      ],
      sqlEyebrow: "Cierre tecnico",
      sqlTitle: "Cierre opcional para audiencias de Fabric, Databricks o Snowflake",
      sqlText: "Si la audiencia es tecnica, termina mostrando que los procesos downstream solo necesitan las vistas activas.",
      sqlExample: `select entity_type_code, source_value, target_value
from vw_mdm_mapping_rule_active
order by entity_type_code, source_value;

select entity_type_code, member_value, group_value
from vw_mdm_group_rule_active
order by entity_type_code, member_value;

select parameter_key, parameter_value, parameter_scope_type, parameter_scope_value
from vw_mdm_parameter_active
where domain = 'demo_training'
order by parameter_scope_type, parameter_scope_value;`,
      secondaryCta: "Abrir aprobaciones",
      steps: [
        {
          kicker: "Paso 1",
          title: "Abrir Equivalencias y mostrar la canonizacion",
          href: "/mappings",
          cta: "Abrir equivalencias",
          text: "Empieza por la pantalla mas intuitiva: dos o mas nombres de origen terminan en un mismo valor canonico.",
          doItems: [
            "Abrir la pagina de Equivalencias.",
            "Filtrar por ACME o COFFEE si quieres una vista mas corta.",
            "Mostrar ejemplos de CLIENT y PRODUCT lado a lado.",
          ],
          lookFor: [
            "ACME S.A. y ACME SA caen en ACME_RETAIL.",
            "CAF 1KG y CAFE MOLIDO 1KG caen en SKU_COFFEE_1KG.",
          ],
        },
        {
          kicker: "Paso 2",
          title: "Abrir Agrupaciones y mostrar segmentacion de negocio",
          href: "/groups",
          cta: "Abrir agrupaciones",
          text: "Despues de canonizar, el producto puede ubicar clientes o productos dentro de grupos orientados al negocio.",
          doItems: [
            "Abrir la pagina de Agrupaciones.",
            "Ubicar ACME_RETAIL y SKU_COFFEE_1KG.",
            "Explicar que esta capa alimenta reporting, planeamiento y pricing.",
          ],
          lookFor: [
            "ACME_RETAIL pertenece a MODERN_TRADE.",
            "SKU_COFFEE_1KG pertenece a HOT_BEVERAGES.",
          ],
        },
        {
          kicker: "Paso 3",
          title: "Abrir Parametros y mostrar reglas operativas",
          href: "/parameters",
          cta: "Abrir parametros",
          text: "Esta pantalla muestra valores que los procesos usan directo, como factores comerciales o margenes minimos.",
          doItems: [
            "Abrir la pagina de Parametros.",
            "Filtrar por demo_training o PVP_FACTOR.",
            "Comparar un parametro con alcance CLIENT y otro con alcance PRODUCT.",
          ],
          lookFor: [
            "ACME_RETAIL tiene un PVP_FACTOR.",
            "SKU_COFFEE_1KG tiene un MIN_MARGIN.",
          ],
        },
        {
          kicker: "Paso 4",
          title: "Abrir Aprobaciones y mostrar trabajo pendiente",
          href: "/approvals",
          cta: "Abrir aprobaciones",
          text: "Aca el producto deja de parecer un visor de tablas y empieza a verse operativo.",
          doItems: [
            "Abrir la pagina de Aprobaciones.",
            "Mostrar la equivalencia, agrupacion y parametro pendientes que dejo la demo.",
            "Explicar que estas propuestas no impactan vistas activas hasta aprobarse.",
          ],
          lookFor: [
            "Una propuesta pendiente de equivalencia para ACME.",
            "Una agrupacion pendiente PREMIUM_BEVERAGES para producto.",
            "Un PVP_FACTOR futuro pendiente para ACME_RETAIL.",
          ],
        },
        {
          kicker: "Paso 5",
          title: "Abrir Auditoria y mostrar trazabilidad",
          href: "/audit",
          cta: "Abrir auditoria",
          text: "Cierra el recorrido probando que cada regla demo tiene historia operativa visible.",
          doItems: [
            "Abrir la pagina de Auditoria.",
            "Filtrar por mdm_mapping_rule o mdm_parameter si quieres una historia mas corta.",
            "Mostrar eventos de create y approve o create y submit.",
          ],
          lookFor: [
            "Eventos create y approve para registros demo aprobados.",
            "Eventos create y submit para registros demo pendientes.",
          ],
        },
      ],
    },
    helpExecutive: {
      faqItems: [
        {
          question: "Que problema resuelve MDM Lite?",
          answer:
            "Resuelve un problema operativo muy comun: reglas pequenas pero criticas que suelen quedar dispersas entre Excel, tablas sueltas y codigo repetido. Centraliza equivalencias, agrupaciones y parametros con vigencia para que los pipelines consuman una version estable.",
        },
        {
          question: "Es un MDM enterprise?",
          answer:
            "No. No busca cubrir golden record, survivorship, workflow complejo, data stewardship extendido ni gobierno corporativo transversal. Cubre un caso mas acotado: reference data y reglas operativas listas para ser consumidas por ETL o ELT.",
        },
        {
          question: "Compite con Purview o Unity Catalog?",
          answer:
            "No de forma directa. Purview, Unity Catalog y herramientas similares gobiernan el ecosistema de datos. MDM Lite administra reglas concretas que ese ecosistema necesita aplicar cuando transforma datos de negocio.",
        },
        {
          question: "Con quien compite de verdad?",
          answer:
            "Compite con tres cosas: plataformas MDM demasiado grandes para el problema, soluciones RDM ligeras mas dispersas y la alternativa real mas comun que es Excel compartido mas tablas auxiliares sin contrato estable.",
        },
        {
          question: "Por que la simplicidad es una ventaja?",
          answer:
            "Porque reduce tiempo de adopcion, dependencia de especialistas y friccion con data engineering. Cuando el problema es puntual, una solucion acotada genera valor antes y con mucho menos costo operativo.",
        },
        {
          question: "Donde encaja en arquitecturas modernas?",
          answer:
            "Encaja en ETL clasico, en ELT, en medallion y en lakehouse. Normalmente se usa en la capa intermedia donde se homologan valores y se aplican reglas antes de publicar datasets curados o marts de negocio.",
        },
      ],
      executiveMessages: [
        "MDM Lite no busca gobernar todos los datos; busca ordenar las reglas que los pipelines usan todos los dias.",
        "Su valor aparece cuando el equipo necesita consistencia operativa sin montar una plataforma enterprise completa.",
        "El contrato tecnico esta en vistas SQL simples, aptas para SQL, dbt, notebooks, Python o pipelines modernos.",
      ],
      eyebrow: "Help / FAQ ejecutiva",
      title: "Preguntas ejecutivas para explicar que es MDM Lite y donde encaja",
      description:
        "Esta pagina sirve para conversaciones cortas con sponsors, arquitectura, gobierno o liderazgo tecnico. Resume el producto sin caer en jerga innecesaria.",
      summaryEyebrow: "Resumen",
      summaryTitle: "Tres ideas para abrir la conversacion",
      shortEyebrow: "Frase corta",
      shortTitle: "Como resumirlo en una reunion",
      shortText:
        "MDM Lite es una capa operativa de reglas maestras simples. No reemplaza catalogo ni gobierno; complementa esas capacidades con homologaciones, agrupaciones y parametros listos para consumo tecnico.",
      questionEyebrow: "Pregunta",
    },
    helpFunctional: {
      contractViews: [
        {
          name: "vw_mdm_mapping_rule_active",
          purpose: "Contrato de lectura para homologar valores origen hacia un canonico antes de consolidar o cargar.",
        },
        {
          name: "vw_mdm_group_rule_active",
          purpose: "Contrato de lectura para agrupar valores ya homologados dentro de una familia comercial o analitica.",
        },
        {
          name: "vw_mdm_parameter_active",
          purpose: "Contrato de lectura para aplicar factores, flags o configuraciones por dominio y alcance.",
        },
      ],
      exampleRows: [
        {
          stage: "Entrada cruda",
          clientSource: "ALDI PORTUGAL",
          groupSource: "ALDI PORTUGAL",
          factorSource: "sin resolver",
          priceSource: "100.00",
          outcome: "Todavia no sirve para reporting porque depende del nombre tal como viene del origen.",
        },
        {
          stage: "Tras equivalencia",
          clientSource: "ALDI",
          groupSource: "ALDI",
          factorSource: "sin resolver",
          priceSource: "100.00",
          outcome: "El cliente ya queda homologado al nombre canonico esperado por el modelo analitico.",
        },
        {
          stage: "Tras agrupacion",
          clientSource: "ALDI",
          groupSource: "GRUPO ALDI",
          factorSource: "sin resolver",
          priceSource: "100.00",
          outcome: "Ahora puede consolidarse en dashboards por grupo comercial y no solo por cliente individual.",
        },
        {
          stage: "Tras parametro",
          clientSource: "ALDI",
          groupSource: "GRUPO ALDI",
          factorSource: "1.08",
          priceSource: "108.00",
          outcome: "El ETL aplica el factor vigente y deja el dato listo para carga analitica o downstream.",
        },
      ],
      optionCards: [
        {
          title: "Equivalencias",
          href: "/mappings",
          whatItIs: "Relaciona un valor origen con un valor canonico o destino para evitar hardcode en procesos y reportes.",
          administration:
            "Se carga cuando un codigo o descripcion externa no coincide con el estandar interno. El admin define desde cuando vale la regla y cual es el valor homologado.",
          fields: ["Entidad", "Clave origen", "Valor origen", "Valor destino", "Vigencia"],
          realUse:
            "En un ETL de ventas, si el ERP manda 'ALDI PORTUGAL' y el modelo analitico espera 'ALDI', la equivalencia resuelve la traduccion antes de cargar el fact table.",
        },
        {
          title: "Agrupaciones",
          href: "/groups",
          whatItIs: "Agrupa multiples valores operativos dentro de una familia comercial o analitica comun.",
          administration:
            "Se usa cuando varios clientes, materiales o codigos deben consolidarse bajo una misma vista de negocio. El admin indica miembro, grupo y vigencia.",
          fields: ["Miembro", "Grupo", "Etiqueta de grupo", "Rule set", "Vigencia"],
          realUse:
            "En un ETL de clientes, 'EROSKI S.COOP.' y otras variantes pueden terminar en el grupo 'EROSKY' para reporting regional o acuerdos comerciales.",
        },
        {
          title: "Parametros",
          href: "/parameters",
          whatItIs: "Guarda valores de configuracion de negocio que cambian con el tiempo o por contexto, sin tocar codigo.",
          administration:
            "Se mantiene cuando una regla depende de un factor, porcentaje o flag por cliente, canal, pais o dominio. El admin define clave, valor, alcance y vigencia.",
          fields: ["Clave", "Valor", "Dominio", "Tipo de alcance", "Valor de alcance", "Vigencia"],
          realUse:
            "En un ETL de pricing, un parametro como 'PVP_FACTOR' puede valer 1.09 para MARJANE y 0.97 para PRIMOR, y el proceso lo consulta al transformar precios.",
        },
        {
          title: "Importacion",
          href: "/imports",
          whatItIs: "Permite cargar lotes demo o archivos manuales csv/xlsx para poblar reglas sin entrar una por una.",
          administration:
            "Se usa cuando llega un archivo del negocio o cuando se quiere reponer un set base. El admin elige tipo de dato, sube el archivo y revisa el resultado.",
          fields: ["Tipo de carga", "Archivo", "Resultado", "Cantidad insertada o actualizada"],
          realUse:
            "En un proceso ETL operativo, negocio entrega un Excel con nuevas homologaciones y el admin lo importa antes de la corrida nocturna.",
        },
      ],
      etlSteps: [
        "El sistema fuente entrega datos crudos con codigos y descripciones no normalizadas.",
        "El ETL extrae esos datos y consulta MDM Lite para buscar equivalencias, agrupaciones y parametros vigentes.",
        "Durante la transformacion, el ETL reemplaza valores origen, consolida grupos y aplica parametros por alcance.",
        "El resultado ya normalizado se carga en tablas analiticas, marts o modelos de reporting.",
        "Si aparece un valor nuevo no contemplado, el admin lo carga en MDM Lite y la siguiente corrida ya lo resuelve sin cambiar codigo.",
      ],
      operatingRules: [
        "Alta manual simple: util para correcciones puntuales o pruebas controladas.",
        "Importacion por archivo: util para volumen, onboarding inicial o mantenimiento periodico.",
        "Vigencia: cada regla debe tener una fecha desde la cual aplica; eso evita sobreescribir historia sin control.",
        "Consumo tecnico: el ETL deberia leer siempre desde las vistas activas para no depender de tablas internas.",
        "Cambio controlado: cuando cambie una regla, conviene crear nueva vigencia antes que editar historia pasada.",
      ],
      eyebrow: "Help / Guia Funcional",
      title: "Que hace cada opcion y como usarla en un caso real de ETL",
      description:
        "Esta guia mantiene el foco original: explicar el sentido funcional de cada modulo, que datos se cargan, como se administran y como se consumen desde procesos tecnicos clasicos.",
      optionEyebrow: "Opcion del menu",
      openOption: "Abrir opcion",
      whatItIsTitle: "Que es",
      administrationTitle: "Como se administra",
      fieldsTitle: "Que se pone",
      realUseTitle: "Uso real en ETL",
      practicalEyebrow: "Flujo Practico",
      practicalTitle: "Como entraria en un ETL real",
      practicalText:
        "Este sigue siendo el recorrido base del MVP cuando lo consumes desde un DW clasico o un proceso batch tradicional.",
      exampleEyebrow: "Ejemplo Detallado",
      exampleTitle: "Antes y despues en una corrida ETL",
      tableHeaders: ["Etapa", "Cliente canonico", "Grupo comercial", "Factor aplicado", "Precio resultante", "Lectura funcional"],
      contractEyebrow: "Contrato Tecnico",
      contractTitle: "Vistas que deberia consumir un proceso",
      contractText: "El contrato recomendado para v0.1 se apoya en vistas activas y no en tablas internas.",
      sqlEyebrow: "Uso desde SQL",
      sqlTitle: "Consulta relacional",
      pythonEyebrow: "Uso desde Python",
      pythonTitle: "Script batch o notebook",
      dbtEyebrow: "Uso desde dbt",
      dbtTitle: "Modelo enriquecido",
      practicesEyebrow: "Buenas practicas",
      practicesTitle: "Como administrarlo bien",
      nextEyebrow: "Siguiente lectura",
      nextTitle: "Para audiencias modernas de data platform",
      nextText:
        "Si la conversacion gira hacia Databricks, Fabric, Snowflake, medallion o ELT, conviene seguir con la pagina dedicada a esos patrones.",
      platformsCta: "Ver medallion y ELT",
      positioningCta: "Ver posicionamiento",
    },
    helpPositioning: {
      complementRows: [
        {
          tool: "Purview / Microsoft Purview",
          strength: "Catalogo, lineage, gobierno, clasificacion y visibilidad transversal.",
          gap: "No esta pensado para operar equivalencias, agrupaciones o parametros de negocio pequenos en el dia a dia.",
          mdmLiteRole:
            "MDM Lite vive abajo de ese nivel: administra reglas concretas que un ETL necesita consultar en tiempo de transformacion.",
        },
        {
          tool: "Unity Catalog",
          strength: "Gobierno de datos, permisos, catalogacion y control sobre activos de Databricks.",
          gap: "No resuelve por si solo el mantenimiento operativo de reglas funcionales tipo nombre canonico, grupo comercial o factor por cliente.",
          mdmLiteRole:
            "MDM Lite puede publicar tablas o vistas gobernadas dentro del ecosistema gobernado por Unity Catalog.",
        },
        {
          tool: "Collibra / Alation / catalogos similares",
          strength: "Definiciones de negocio, ownership, discovery y governance operating model.",
          gap: "Suelen estar mas orientados a metadata y gobierno que a una operacion simple de reglas con alta, edicion e integracion inmediata en pipelines.",
          mdmLiteRole:
            "MDM Lite cubre el hueco operativo entre la definicion conceptual y la aplicacion tecnica de la regla.",
        },
      ],
      competitorRows: [
        {
          type: "MDM enterprise clasico",
          examples: "Informatica MDM, Reltio, Semarchy xDM, Profisee, SAP MDG",
          fit: "Compiten en el espacio amplio de master data management, workflow, golden record, survivorship y gobierno avanzado.",
          difference:
            "MDM Lite no intenta cubrir ese ancho. Gana cuando el problema real es mas pequeno, puntual y orientado a consumo tecnico rapido.",
        },
        {
          type: "Reference data manager especifico",
          examples: "soluciones de RDM o implementaciones ligeras sobre tablas y APIs",
          fit: "Compiten mas directamente cuando el objetivo es mantener catalogos operativos y reglas simples.",
          difference:
            "MDM Lite busca ser mas claro, explicable y listo para ETL que una coleccion dispersa de tablas custom.",
        },
        {
          type: "Implementacion casera",
          examples: "Excel compartido, CSV versionados, tablas sueltas en un schema utilitario",
          fit: "Es la alternativa real mas comun en equipos pequenos o medianos.",
          difference:
            "Ahi la simplicidad es un valor enorme: MDM Lite ordena ese caos con una UI minima, vigencia y contratos de lectura estables.",
        },
      ],
      simplicityPoints: [
        "Menor costo de adopcion: un admin puede entenderlo y usarlo rapido.",
        "Menor complejidad tecnica: vistas SQL y formularios simples en lugar de plataformas pesadas.",
        "Menor friccion con data engineering: el consumo tecnico es obvio y directo.",
        "Mejor encaje en equipos que todavia no justifican un MDM enterprise.",
        "Valor alto para huecos pequenos pero recurrentes: homologaciones, grupos y parametros funcionales.",
      ],
      positioningMessages: [
        "No competimos con herramientas de catalogo y gobierno; las complementamos.",
        "No reemplazamos lineage, permisos, clasificacion, ownership ni discovery.",
        "Competimos de verdad contra soluciones demasiado pesadas o contra el caos de Excel + tablas sueltas.",
        "La propuesta de valor no es amplitud funcional, sino velocidad, claridad y simplicidad operativa.",
      ],
      eyebrow: "Help / Posicionamiento",
      title: "Como se posiciona frente a Purview, Unity Catalog y otras herramientas",
      description:
        "Esta pagina deja claro donde encaja MDM Lite para que no se lea como competidor de plataformas de gobierno o catalogo.",
      centralEyebrow: "Mensaje central",
      centralTitle: "Complemento, no reemplazo",
      readingEyebrow: "Lectura recomendada",
      readingTitle: "Como explicarlo rapido",
      readingText:
        "Purview, Unity Catalog o Collibra gobiernan el ecosistema de datos. MDM Lite opera reglas chicas y criticas que el ETL necesita aplicar de verdad.",
      visualEyebrow: "Mapa visual",
      visualTitle: "Donde se ubica MDM Lite",
      governanceKicker: "Gobierno y catalogo",
      governanceText: "Descubrimiento, ownership, permisos, lineage y visibilidad transversal.",
      operationsKicker: "Operacion de reglas",
      operationsText: "Equivalencias, agrupaciones y parametros vigentes usados por transformaciones reales.",
      consumptionKicker: "Consumo",
      consumptionText: "Aplicacion consistente de reglas en ETL, ELT, marts y semantic layers.",
      complementEyebrow: "Comparacion",
      complementTitle: "Con que se complementa",
      complementHeaders: ["Herramienta", "Valor principal", "Hueco habitual", "Rol de MDM Lite"],
      competitorsEyebrow: "Competencia",
      competitorsTitle: "Con quien si competimos",
      competitorHeaders: ["Espacio", "Ejemplos", "Donde compite", "Diferencia de MDM Lite"],
      valueEyebrow: "Valor",
      valueTitle: "Por que la simplicidad importa",
      shortEyebrow: "Frase corta",
      shortTitle: "Como resumir el encaje",
      shortText:
        "Purview o Unity Catalog te dicen que datos existen, quien los gobierna y como se controlan. MDM Lite te ayuda a decidir como transformar ciertos valores de negocio para que esos datos sean consumibles de manera consistente.",
    },
    helpPlatforms: {
      medallionRows: [
        {
          layer: "Bronze / Raw",
          role: "Conservar el dato tal como llega desde la fuente.",
          mdmUsage: "Normalmente MDM Lite no modifica Bronze. A lo sumo sirve para detectar valores nuevos que todavia no estan mapeados.",
        },
        {
          layer: "Silver / Cleansed",
          role: "Normalizar, enriquecer y dejar el dato usable para modelos posteriores.",
          mdmUsage: "Este es el lugar natural para aplicar equivalencias, agrupaciones y parametros. Aca MDM Lite agrega mas valor.",
        },
        {
          layer: "Gold / Business-ready",
          role: "Publicar datasets curados para BI, semantic layer o consumo de negocio.",
          mdmUsage: "Gold recibe el dato ya homologado desde Silver. MDM Lite no suele operar directo aca, pero su efecto se ve clarisimo en dashboards y metricas.",
        },
      ],
      platformPatterns: [
        {
          platform: "Databricks",
          pattern: "Tablas o vistas curadas en Unity Catalog, notebooks o jobs que leen reglas desde PostgreSQL o desde una replica controlada.",
        },
        {
          platform: "Microsoft Fabric",
          pattern: "Dataflows, notebooks o pipelines que consultan vistas activas para enriquecer capas Silver y Gold.",
        },
        {
          platform: "Snowflake",
          pattern: "ELT en SQL o dbt consumiendo vistas activas para normalizacion antes de marts o semantic models.",
        },
      ],
      eltMessages: [
        "En ELT, la transformacion vive dentro del engine analitico, pero igual necesita una fuente de reglas estable.",
        "MDM Lite no impone un runtime: puede alimentar SQL, dbt, notebooks, stored procedures o pipelines orquestados.",
        "El patron correcto es exponer reglas simples como datos consultables, no como codigo repetido en cada modelo.",
        "En lakehouse y warehouse modernos, el problema sigue existiendo: nombres distintos, grupos comerciales y factores funcionales siguen apareciendo.",
      ],
      recommendedPatterns: [
        "Tratar MDM Lite como reference dataset externo y estable.",
        "Aplicar equivalencias primero, luego agrupaciones y al final parametros.",
        "Resolver transformaciones en Silver o en la capa intermedia equivalente.",
        "Publicar Gold o marts ya con datos canonicos y reglas aplicadas.",
        "Mantener el contrato tecnico en vistas para no acoplar pipelines a tablas internas.",
      ],
      antiPatterns: [
        "Aplicar reglas distintas en cada notebook o modelo sin una fuente comun.",
        "Mantener homologaciones en hojas sueltas fuera del pipeline controlado.",
        "Usar Gold como lugar para corregir nombres que debieron resolverse antes.",
        "Embeber listas de equivalencias en codigo Python, SQL o YAML disperso.",
        "Acoplarse a tablas internas en lugar de vistas activas.",
      ],
      eyebrow: "Help / Medallion y ELT",
      title: "Como encaja en Databricks, Fabric, Snowflake y arquitecturas modernas",
      description:
        "Esta pagina traduce el MVP a lenguajes mas actuales: medallion, ELT, lakehouse, semantic layer y pipelines modernos.",
      centralEyebrow: "Mensaje central",
      centralTitle: "Medallion no elimina la necesidad de reglas maestras",
      centralText:
        "Aunque cambie el stack, siguen llegando nombres inconsistentes, codigos externos, agrupaciones de negocio y parametros que cambian en el tiempo.",
      eltEyebrow: "ELT",
      eltTitle: "Que cambia frente al ETL clasico",
      visualEyebrow: "Mapa visual",
      visualTitle: "Ubicacion tipica en arquitectura medallion",
      bronzeText: "Entrada casi intacta desde ERP, CRM, archivos o APIs.",
      silverText: "Homologacion, agrupacion y parametros antes de publicar datasets curados.",
      goldText: "Dashboards, marts, semantic models y analitica sobre valores canonicos.",
      medallionEyebrow: "Medallion",
      medallionTitle: "En que capa vive el valor de MDM Lite",
      medallionHeaders: ["Capa", "Rol", "Uso recomendado de MDM Lite"],
      platformsEyebrow: "Plataformas",
      platformsTitle: "Patrones tipicos por ecosistema",
      platformHeaders: ["Plataforma", "Patron de integracion"],
      recommendedEyebrow: "Patron recomendado",
      recommendedTitle: "Como integrarlo bien",
      antiEyebrow: "Anti-patrones",
      antiTitle: "Que conviene evitar",
      quickEyebrow: "Lectura rapida",
      quickTitle: "Patron moderno resumido",
      rulesKicker: "Fuente de reglas",
      rulesText: "PostgreSQL con vistas activas como contrato estable y desacoplado de tablas internas.",
      engineKicker: "Motor de transformacion",
      engineText: "Aplicacion centralizada de reglas en la capa intermedia.",
      outputKicker: "Salida",
      outputText: "Consumo uniforme sobre datos ya homologados.",
    },
  },
};

export function getCopy(language: AppLanguage) {
  return copy[language];
}